env:
  browser: true
  commonjs: true
  es6: true
extends:
  - airbnb-base
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2018
plugins:
  - '@typescript-eslint'
rules: {
  "no-unused-vars": "off",
  "@typescript-eslint/no-unused-vars": "error",
  "import/extensions" : "off",
  "import/no-unresolved": "off",
  "import/prefer-default-export": "off",
  "no-multi-assign": "off",
  "no-plusplus" : "off",
  "no-mixed-operators": "off",
  "class-methods-use-this" : "off",
  "no-useless-constructor" : "off",
  "no-empty-function"   : "off",
  "no-return-await" : "off",
  "no-continue" : "off",
  "new-cap" : "off",
  "consistent-return" : "off",

  "semi": ["error", "never", {"beforeStatementContinuationChars": "never"}],
  "semi-spacing": ["error", {"after": true, "before": false}],
  "semi-style": ["error", "first"],
  "no-extra-semi": "error",
  "no-unexpected-multiline": "error",
  "no-unreachable": "error"
}
